version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: jetson-jupyter-lab
    container_name: jetson-jupyter-container
    volumes:
      - ./notebooks:/workspace/notebooks  # Mount your local notebooks directory
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"] # no token or password initially.
    ports:
      - 8888:8888
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  
    user: root # Use root for better permissions initially.
